/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jogo2048.Elemento;
import jogo2048.Tabuleiro;

/**
 *
 * @author marco
 */
public class TelaPrincipal extends javax.swing.JFrame implements KeyListener{
    private Tabuleiro tab;
    /**
     * Creates new form TelaPrincipalDoJogo
     */
    public TelaPrincipal(Tabuleiro tab) {
        initComponents();
        addKeyListener(this);
        setFocusable(true);
        this.tab = tab;
        icon();
        this.setLocationRelativeTo(null);
    }
    
    public void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..\\imagens\\IconeJogo.png")));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel01 = new javax.swing.JPanel();
        jLabel01 = new javax.swing.JLabel();
        jPanel02 = new javax.swing.JPanel();
        jLabel02 = new javax.swing.JLabel();
        jPanel03 = new javax.swing.JPanel();
        jLabel03 = new javax.swing.JLabel();
        jPanel04 = new javax.swing.JPanel();
        jLabel04 = new javax.swing.JLabel();
        jPanel05 = new javax.swing.JPanel();
        jLabel05 = new javax.swing.JLabel();
        jPanel07 = new javax.swing.JPanel();
        jLabel07 = new javax.swing.JLabel();
        jPanel08 = new javax.swing.JPanel();
        jLabel08 = new javax.swing.JLabel();
        jPanel06 = new javax.swing.JPanel();
        jLabel06 = new javax.swing.JLabel();
        jPanel09 = new javax.swing.JPanel();
        jLabel09 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtScore = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("2048");
        setBackground(new java.awt.Color(153, 153, 153));
        setLocation(new java.awt.Point(600, 170));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 248, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 80));

        jPanel2.setBackground(new java.awt.Color(187, 173, 160));
        jPanel2.setForeground(new java.awt.Color(187, 173, 160));

        jPanel01.setBackground(new java.awt.Color(205, 193, 180));
        jPanel01.setForeground(new java.awt.Color(205, 193, 180));
        jPanel01.setMinimumSize(new java.awt.Dimension(125, 125));
        jPanel01.setPreferredSize(new java.awt.Dimension(125, 125));

        jLabel01.setBackground(new java.awt.Color(119, 110, 101));
        jLabel01.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel01.setForeground(new java.awt.Color(119, 110, 101));
        jLabel01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel01.setText(" 11");
        jLabel01.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel01.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel01Layout = new javax.swing.GroupLayout(jPanel01);
        jPanel01.setLayout(jPanel01Layout);
        jPanel01Layout.setHorizontalGroup(
            jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel01Layout.setVerticalGroup(
            jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel02.setBackground(new java.awt.Color(205, 193, 180));
        jPanel02.setForeground(new java.awt.Color(205, 193, 180));
        jPanel02.setMinimumSize(new java.awt.Dimension(125, 125));
        jPanel02.setPreferredSize(new java.awt.Dimension(125, 125));

        jLabel02.setBackground(new java.awt.Color(119, 110, 101));
        jLabel02.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel02.setForeground(new java.awt.Color(119, 110, 101));
        jLabel02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel02.setText(" 11");
        jLabel02.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel02.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel02Layout = new javax.swing.GroupLayout(jPanel02);
        jPanel02.setLayout(jPanel02Layout);
        jPanel02Layout.setHorizontalGroup(
            jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel02Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel02Layout.setVerticalGroup(
            jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel02Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel03.setBackground(new java.awt.Color(205, 193, 180));
        jPanel03.setForeground(new java.awt.Color(205, 193, 180));
        jPanel03.setMinimumSize(new java.awt.Dimension(125, 125));
        jPanel03.setPreferredSize(new java.awt.Dimension(125, 125));

        jLabel03.setBackground(new java.awt.Color(119, 110, 101));
        jLabel03.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel03.setForeground(new java.awt.Color(119, 110, 101));
        jLabel03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel03.setText(" 11");
        jLabel03.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel03Layout = new javax.swing.GroupLayout(jPanel03);
        jPanel03.setLayout(jPanel03Layout);
        jPanel03Layout.setHorizontalGroup(
            jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel03Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel03Layout.setVerticalGroup(
            jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel03Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel04.setBackground(new java.awt.Color(205, 193, 180));
        jPanel04.setForeground(new java.awt.Color(205, 193, 180));
        jPanel04.setMinimumSize(new java.awt.Dimension(125, 125));
        jPanel04.setPreferredSize(new java.awt.Dimension(125, 125));

        jLabel04.setBackground(new java.awt.Color(119, 110, 101));
        jLabel04.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel04.setForeground(new java.awt.Color(119, 110, 101));
        jLabel04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel04.setText(" 11");
        jLabel04.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel04Layout = new javax.swing.GroupLayout(jPanel04);
        jPanel04.setLayout(jPanel04Layout);
        jPanel04Layout.setHorizontalGroup(
            jPanel04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel04Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel04Layout.setVerticalGroup(
            jPanel04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel04Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel05.setBackground(new java.awt.Color(205, 193, 180));
        jPanel05.setForeground(new java.awt.Color(205, 193, 180));
        jPanel05.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel05.setBackground(new java.awt.Color(119, 110, 101));
        jLabel05.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel05.setForeground(new java.awt.Color(119, 110, 101));
        jLabel05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel05.setText(" 11");
        jLabel05.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel05.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel05Layout = new javax.swing.GroupLayout(jPanel05);
        jPanel05.setLayout(jPanel05Layout);
        jPanel05Layout.setHorizontalGroup(
            jPanel05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel05Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel05Layout.setVerticalGroup(
            jPanel05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel05Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel07.setBackground(new java.awt.Color(205, 193, 180));
        jPanel07.setForeground(new java.awt.Color(205, 193, 180));
        jPanel07.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel07.setBackground(new java.awt.Color(119, 110, 101));
        jLabel07.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel07.setForeground(new java.awt.Color(119, 110, 101));
        jLabel07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel07.setText(" 11");
        jLabel07.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel07.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel07Layout = new javax.swing.GroupLayout(jPanel07);
        jPanel07.setLayout(jPanel07Layout);
        jPanel07Layout.setHorizontalGroup(
            jPanel07Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel07Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel07Layout.setVerticalGroup(
            jPanel07Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel07Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel08.setBackground(new java.awt.Color(205, 193, 180));
        jPanel08.setForeground(new java.awt.Color(205, 193, 180));
        jPanel08.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel08.setBackground(new java.awt.Color(119, 110, 101));
        jLabel08.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel08.setForeground(new java.awt.Color(119, 110, 101));
        jLabel08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel08.setText(" 11");
        jLabel08.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel08.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel08Layout = new javax.swing.GroupLayout(jPanel08);
        jPanel08.setLayout(jPanel08Layout);
        jPanel08Layout.setHorizontalGroup(
            jPanel08Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel08Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel08Layout.setVerticalGroup(
            jPanel08Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel08Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel06.setBackground(new java.awt.Color(205, 193, 180));
        jPanel06.setForeground(new java.awt.Color(205, 193, 180));
        jPanel06.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel06.setBackground(new java.awt.Color(119, 110, 101));
        jLabel06.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel06.setForeground(new java.awt.Color(119, 110, 101));
        jLabel06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel06.setText(" 11");
        jLabel06.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel06.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel06Layout = new javax.swing.GroupLayout(jPanel06);
        jPanel06.setLayout(jPanel06Layout);
        jPanel06Layout.setHorizontalGroup(
            jPanel06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel06Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel06Layout.setVerticalGroup(
            jPanel06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel06Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel09.setBackground(new java.awt.Color(205, 193, 180));
        jPanel09.setForeground(new java.awt.Color(205, 193, 180));
        jPanel09.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel09.setBackground(new java.awt.Color(119, 110, 101));
        jLabel09.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel09.setForeground(new java.awt.Color(119, 110, 101));
        jLabel09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel09.setText(" 11");
        jLabel09.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel09.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel09Layout = new javax.swing.GroupLayout(jPanel09);
        jPanel09.setLayout(jPanel09Layout);
        jPanel09Layout.setHorizontalGroup(
            jPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel09Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel09Layout.setVerticalGroup(
            jPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel09Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(205, 193, 180));
        jPanel12.setForeground(new java.awt.Color(205, 193, 180));
        jPanel12.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel12.setBackground(new java.awt.Color(119, 110, 101));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(119, 110, 101));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" 11");
        jLabel12.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel12.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(205, 193, 180));
        jPanel11.setForeground(new java.awt.Color(205, 193, 180));
        jPanel11.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel11.setBackground(new java.awt.Color(119, 110, 101));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(119, 110, 101));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" 11");
        jLabel11.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel11.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel10.setBackground(new java.awt.Color(205, 193, 180));
        jPanel10.setForeground(new java.awt.Color(205, 193, 180));
        jPanel10.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel10.setBackground(new java.awt.Color(119, 110, 101));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(119, 110, 101));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" 11");
        jLabel10.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel10.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel13.setBackground(new java.awt.Color(205, 193, 180));
        jPanel13.setForeground(new java.awt.Color(205, 193, 180));
        jPanel13.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel13.setBackground(new java.awt.Color(119, 110, 101));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(119, 110, 101));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(" 11");
        jLabel13.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel13.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel16.setBackground(new java.awt.Color(205, 193, 180));
        jPanel16.setForeground(new java.awt.Color(205, 193, 180));
        jPanel16.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel16.setBackground(new java.awt.Color(119, 110, 101));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(119, 110, 101));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(" 11");
        jLabel16.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel16.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel15.setBackground(new java.awt.Color(205, 193, 180));
        jPanel15.setForeground(new java.awt.Color(205, 193, 180));
        jPanel15.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel15.setBackground(new java.awt.Color(119, 110, 101));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(119, 110, 101));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" 11");
        jLabel15.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel15.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel14.setBackground(new java.awt.Color(205, 193, 180));
        jPanel14.setForeground(new java.awt.Color(205, 193, 180));
        jPanel14.setMinimumSize(new java.awt.Dimension(125, 125));

        jLabel14.setBackground(new java.awt.Color(119, 110, 101));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(119, 110, 101));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" 11");
        jLabel14.setMaximumSize(new java.awt.Dimension(78, 60));
        jLabel14.setPreferredSize(new java.awt.Dimension(60, 50));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel09, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel06, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel05, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel07, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel09, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(245, 138, 60));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(0, 0, 153));

        jPanel4.setBackground(new java.awt.Color(26, 108, 145));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        txtScore.setBackground(new java.awt.Color(0, 0, 0));
        txtScore.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtScore.setForeground(new java.awt.Color(255, 255, 255));
        txtScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtScore.setText("2048");
        txtScore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Score");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void alterarTextoMatriz(int[][] matrizEntrada){
        javax.swing.JLabel[][] labels = {{jLabel01,jLabel02,jLabel03,jLabel04},{jLabel05,jLabel06,jLabel07,jLabel08},{jLabel09,jLabel10,jLabel11,jLabel12},{jLabel13,jLabel14,jLabel15,jLabel16}};
        
        for (int linha = 0; linha < labels.length; linha++) {
            for (int coluna = 0; coluna < labels[linha].length; coluna++) {
                if(matrizEntrada[linha][coluna]!=0){
                    labels[linha][coluna].setText(""+matrizEntrada[linha][coluna]);
                }
                else{
                    labels[linha][coluna].setText("");
                }
            }
        }
    }
    
    
    public void setComponentes(Elemento[][] matrizElementos){
        
        javax.swing.JLabel[][] labels = {{jLabel01,jLabel02,jLabel03,jLabel04},{jLabel05,jLabel06,jLabel07,jLabel08},{jLabel09,jLabel10,jLabel11,jLabel12},{jLabel13,jLabel14,jLabel15,jLabel16}};
        javax.swing.JPanel[][] panels = {{jPanel01,jPanel02,jPanel03,jPanel04},{jPanel05,jPanel06,jPanel07,jPanel08},{jPanel09,jPanel10,jPanel11,jPanel12},{jPanel13,jPanel14,jPanel15,jPanel16}};
        
        //Cores texto e quadrado
        int redTexto, greenTexto, blueTexto;
        int redQuadrado, greenQuadrado, blueQuadrado;
        
        //Add Score
        txtScore.setText(""+tab.getScore());
        
        //ALTERAR TEXTO e CORES
        for (int linha = 0; linha < matrizElementos.length; linha++) {
            for (int coluna = 0; coluna < matrizElementos[linha].length; coluna++) {
                
                redTexto = matrizElementos[linha][coluna].getCorTexto()[0];
                greenTexto = matrizElementos[linha][coluna].getCorTexto()[1];
                blueTexto = matrizElementos[linha][coluna].getCorTexto()[2];
                
                redQuadrado = matrizElementos[linha][coluna].getCorQuadrado()[0];
                greenQuadrado = matrizElementos[linha][coluna].getCorQuadrado()[1];
                blueQuadrado = matrizElementos[linha][coluna].getCorQuadrado()[2];
                
                //MUDAR TEXTO
                if(matrizElementos[linha][coluna].getValor()!=0){
                    labels[linha][coluna].setText(""+matrizElementos[linha][coluna].getValor());
                }
                else{
                    labels[linha][coluna].setText("");
                }
                
                //MUDAR CORES
                labels[linha][coluna].setForeground(new java.awt.Color(redTexto, greenTexto, blueTexto));
                labels[linha][coluna].setBackground(new java.awt.Color(redTexto, greenTexto, blueTexto));
                panels[linha][coluna].setForeground(new java.awt.Color(redQuadrado, greenQuadrado, blueQuadrado));
                panels[linha][coluna].setBackground(new java.awt.Color(redQuadrado, greenQuadrado, blueQuadrado));
                
            }
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal(new Tabuleiro(4,4,2)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel01;
    private javax.swing.JLabel jLabel02;
    private javax.swing.JLabel jLabel03;
    private javax.swing.JLabel jLabel04;
    private javax.swing.JLabel jLabel05;
    private javax.swing.JLabel jLabel06;
    private javax.swing.JLabel jLabel07;
    private javax.swing.JLabel jLabel08;
    private javax.swing.JLabel jLabel09;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel01;
    private javax.swing.JPanel jPanel02;
    private javax.swing.JPanel jPanel03;
    private javax.swing.JPanel jPanel04;
    private javax.swing.JPanel jPanel05;
    private javax.swing.JPanel jPanel06;
    private javax.swing.JPanel jPanel07;
    private javax.swing.JPanel jPanel08;
    private javax.swing.JPanel jPanel09;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtScore;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
        if(tab.isLose()){
            JOptionPane.showMessageDialog(this, "Infelizmente você perdeu, tente novamente outra vez","Derrota" , JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        else if(tab.isWin()){
            JOptionPane.showMessageDialog(this, "Parabéns!! Você ganhou o 2048!","Vitória" , JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        
        //CIMA
        else if((e.getKeyChar()=='w')&tab.isMovCima()){
            tab.moverCima();
            tab.gerarNovo2();
        }
        else if((e.getKeyChar()=='w')&tab.isMovCima()==false){   //Controle de excessâo
            JOptionPane.showMessageDialog(this, "Você não pode se mover para cima", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
       
        //ESQUERDA
        else if((e.getKeyChar()=='a')&tab.isMovEsquerda()){
            tab.moverEsquerda();
            tab.gerarNovo2();
        }
        else if((e.getKeyChar()=='a')&tab.isMovEsquerda()==false){   //Controle de excessâo
            JOptionPane.showMessageDialog(this, "Você não pode se mover para esquerda", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
       
        //BAIXO
        else if((e.getKeyChar()=='s')&tab.isMovBaixo()){
            tab.moverBaixo();
            tab.gerarNovo2();
        }
        else if((e.getKeyChar()=='s')&tab.isMovBaixo()==false){   //Controle de excessâo
            JOptionPane.showMessageDialog(this, "Você não pode se mover para baixo", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
       
        //DIREITA
        else if((e.getKeyChar()=='d')&tab.isMovDireita()){
            tab.moverDireita();
            tab.gerarNovo2();
        }
        else if((e.getKeyChar()=='d')&tab.isMovDireita()==false){   //Controle de excessâo
            JOptionPane.showMessageDialog(this, "Você não pode se mover para direita", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        //Atualiza matrizElementos da tabela e seta os componentes desse objeto
        tab.setElementos();
        this.setComponentes(tab.getMatrizElemento());
        this.setVisible(true);

    }
}
